### PR TITLE
Sort people by name

### PR DESCRIPTION
**Pull request by erino**

### CODE REVIEW

**Comment by calumgunn** [comment]
:+1:

**Comment by annagoss** [comment]
What does this do?

**Comment by erino** [comment]
The select where you choose who you are is now sorted alphabetically

**Comment by annagoss** [comment]
:+1:

**Comment by jgwhite** [comment]
I couldn’t help but notice it also adds a new gem dependency and removes some code climate config :trollface:

**Comment by jgwhite** [comment]
(not that I disapprove of either of those changes)

**Comment by erino** [comment]
yep, maybe that should have been in a separate PR... :flushed:

**Pull request merged**
